pub mod antivirus;
pub mod arc;
pub mod attachment;
pub mod bulk;
pub mod charset;
pub mod content;
pub mod dkim;
pub mod dmarc;
pub mod header_analysis;
pub mod html;
pub mod ratio;
pub mod url_analysis;

pub use antivirus::{AntivirusCheck, ScannerDef};
pub use arc::ArcCheck;
pub use attachment::AttachmentCheck;
pub use bulk::BulkDetectionCheck;
pub use charset::CharsetCheck;
pub use content::{ContentCheck, ContentRule};
pub use dkim::DkimCheck;
pub use dmarc::DmarcCheck;
pub use header_analysis::HeaderAnalysisCheck;
pub use html::HtmlAnalysisCheck;
pub use ratio::RatioAnalysisCheck;
pub use url_analysis::UrlAnalysisCheck;
