FROM rockylinux:8

RUN dnf install -y \
    curl \
    pkgconf-pkg-config \
    openssl-devel \
    cmake \
    perl \
    gcc \
    gcc-c++ \
    make \
    && dnf clean all

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs \
    | sh -s -- -y --default-toolchain 1.88.0 --profile minimal
ENV PATH="/root/.cargo/bin:${PATH}"

WORKDIR /app

CMD ["cargo", "build"]
